[build]
  command = "hugo"
  publish = "public"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture --baseURL /"
  HUGO_VERSION = "0.24.1"

[context.production.environment]
  HUGO_VERSION = "0.24.1"