[build]
  command = "hugo"
  publish = "public"

[context.deploy-preview]
  HUGO_VERSION = "0.24"
  command = "hugo version"
  command = "hugo --buildDrafts --buildFuture --baseURL /"

[context.production.environment]
  HUGO_VERSION = "0.24"