[context.production.environment]
  HUGO_VERSION = "0.32.4"

[context.deploy-preview]
  HUGO_VERSION = "0.32.4"
  command = "hugo --buildDrafts --buildFuture --baseURL /"

[context.branch-deploy]
  HUGO_VERSION = "0.32.4"
  command = "hugo --buildDrafts --buildFuture --baseURL /"