[context.production.environment]
  HUGO_VERSION = "0.33"

[context.deploy-preview]
  HUGO_VERSION = "0.33"
  command = "hugo --buildDrafts --buildFuture"

[context.branch-deploy]
  HUGO_VERSION = "0.33"
  command = "hugo --buildDrafts --buildFuture"