[context.deploy-preview]
  HUGO_VERSION = "0.24.1"
  command = "hugo --buildDrafts --buildFuture --baseURL /"

[context.branch-deploy]
  HUGO_VERSION = "0.24.1"
  command = "hugo --buildDrafts --buildFuture --baseURL /"