[context.production.environment]
  HUGO_VERSION = "0.40.2"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture --baseURL /"
  [context.deploy-preview.environment]
    HUGO_VERSION = "0.40.2"

[context.branch-deploy]
  command = "hugo --buildDrafts --buildFuture --baseURL /"
  [context.branch-deploy.environment]
    HUGO_VERSION = "0.40.2"
